### ISSUE TITLE
web-ext lint is reporting png icon files as corrupted when linting an unpacked extension

### ISSUE THREAD

**Issue by rpl** [mozilla/web-ext#1164]
### Is this a feature request or a bug?

bug

### What is the current behavior?

- clone the mdn/webextensions-examples repo
- web-ext lint -s webextensions-examples/beatify

```
Validation Summary:

errors          0
notices         0
warnings        1

WARNINGS:

Code                Message              Description                                                File            Line   Column
CORRUPT_ICON_FILE   Corrupt image file   Expected icon file at "icons/beasts-48.png" is corrupted   manifest.json
```  

on the contrary if we run `web-ext lint` on the same extension packed into a zip file (by packing the same directory content and then run `web-ext lint -s webextensions-examples/beastify.xpi`):

```
Validation Summary:

errors          0
notices         0
warnings        1

WARNINGS:

Code                Message                               Description                                                               File            Line   Column
ICON_SIZE_INVALID   The size of the icon does not match   Expected icon at "icons/beasts-48.png" to be 48 pixels wide but was 60.   manifest.json
                    the manifest.
``` 

web-ext lint is reporting the image as corrupted when running against the unpacked extension, while it reports a invalid size as expected when running against the zip file. 

### What is the expected or desired behavior?

web-ext lint should not report a corrupted image when running against an unpacked extension, on the contrary it should have the same behavior of running it against the zip file (e.g. by reporting the invalid size when the png file doesn't have the expected size, or no errors if the icon file doesn't have any validation issues).

### Version information (for bug reports)

The issue is currently only reproducible on the web-ext version built from the master branch, due to the addons-linter 0.30.0 dependency, and the upstream issue is currently tracked by the following addons-linter pull request:

- https://github.com/mozilla/addons-linter/pull/1714

**Comment by kumar303** [comment]
Fixed in https://github.com/mozilla/web-ext/pull/1165

**Comment by AlexandraMoga** [comment]
I've tried to validate an extension using `web-ext lint` and I have the following results:
- when validating an un-packed directory I receive the following error: `MANIFEST_ICON_NOT_FOUND`
- when validating a packed directory no errors or warnings are thrown

the extension used for this test is the following (taken from [mdn/webextensions-examples](https://github.com/mdn/webextensions-examples)):

[beastify.zip](https://github.com/mozilla/web-ext/files/1579566/beastify.zip)

**Comment by kumar303** [comment]
Hi @AlexandraMoga . Thanks for testing out the fix. However, it has not been released yet. How did you install `web-ext`? You would need to [install it from source](https://github.com/mozilla/web-ext/blob/master/README.md#installation-from-source) to see the fix.

**Comment by AlexandraMoga** [comment]
Hi @kumar303 . After installing `web-ext` from the source mentioned, here is what I get:
- when validating a packed directory, I receive a warning `ICON_SIZE_INVALID` - as expected
- when validating an un-packed directory I still receive the following error: `MANIFEST_ICON_NOT_FOUND`

Veified on WIn10x64
